obj-$(CONFIG_HISENSE_BOOT_INFO) += bootinfo.o
obj-$(CONFIG_HISENSE_DEBUG_RESUME_SUSPEND) += hisresume.o
obj-$(CONFIG_HISENSE_FUSE_STATUS) += hisfuse.o
obj-$(CONFIG_HISENSE_SHOW_BOOT_LOG) += his_boot_log.o

obj-$(CONFIG_HISENSE_EMMC_OPS) += his_emmc_ops.o
obj-$(CONFIG_HISENSE_DBG_CTRL_NODE) += his_debug_control_node.o
obj-$(CONFIG_HISENSE_NO_SD_RAMDUMP) += his_no_sd_ramdump.o

obj-$(CONFIG_SUBSYS_ERR_REPORT)     +=  subsys_err_report.o
obj-$(CONFIG_HISENSE_SERIAL_CONSOLE_CONTROL)     += his_serial_control.o

obj-$(CONFIG_RS_RECORDER_SUPPORT)           +=   rs_recorder/
